/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.swing;

/**
 *
 * @author EduardoPatricia
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaBemVindo = new javax.swing.JInternalFrame();
        jPanelBemVindo = new javax.swing.JPanel();
        jButtonMedicao = new javax.swing.JButton();
        jButtonIniciarAula = new javax.swing.JButton();
        jButtonReceber = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroaluno = new javax.swing.JMenuItem();
        jMenuItemCadastroProfessor = new javax.swing.JMenuItem();
        jMenuItemCadastroAula = new javax.swing.JMenuItem();
        jMenuFinancas = new javax.swing.JMenu();
        jMenuItemMensalidade = new javax.swing.JMenuItem();
        jMenuItemPagarConta = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuBemVindo = new javax.swing.JMenuItem();
        jMenuEvolucao = new javax.swing.JMenuItem();
        jMenuDivedores = new javax.swing.JMenuItem();
        jMenuBalanco = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equilibrio Academia");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        TelaBemVindo.setTitle("Bem Vindo ao Sistema");
        TelaBemVindo.setVisible(true);

        jButtonMedicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/imagens/torax.jpg"))); // NOI18N
        jButtonMedicao.setToolTipText("Iniciar uma Medicao");
        jButtonMedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicaoActionPerformed(evt);
            }
        });

        jButtonIniciarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/imagens/treino.png"))); // NOI18N
        jButtonIniciarAula.setToolTipText("Iniciar uma aula");
        jButtonIniciarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarAulaActionPerformed(evt);
            }
        });

        jButtonReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/imagens/dinheiro.png"))); // NOI18N
        jButtonReceber.setToolTipText("Receber Mensalidade");
        jButtonReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBemVindoLayout = new javax.swing.GroupLayout(jPanelBemVindo);
        jPanelBemVindo.setLayout(jPanelBemVindoLayout);
        jPanelBemVindoLayout.setHorizontalGroup(
            jPanelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBemVindoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButtonIniciarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButtonMedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButtonReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelBemVindoLayout.setVerticalGroup(
            jPanelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBemVindoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIniciarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("Fechar Tela Bem Vindo");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaBemVindoLayout = new javax.swing.GroupLayout(TelaBemVindo.getContentPane());
        TelaBemVindo.getContentPane().setLayout(TelaBemVindoLayout);
        TelaBemVindoLayout.setHorizontalGroup(
            TelaBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaBemVindoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaBemVindoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );
        TelaBemVindoLayout.setVerticalGroup(
            TelaBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaBemVindoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonSair)
                .addGap(18, 18, 18)
                .addComponent(jPanelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(TelaBemVindo);
        TelaBemVindo.setBounds(80, 50, 840, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 540);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setToolTipText("Gerenciamento de Cadastro");

        jMenuItemCadastroaluno.setText("Incluir");
        jMenuItemCadastroaluno.setToolTipText("Inclui Pessoas no Cadastro");
        jMenuItemCadastroaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroalunoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroaluno);

        jMenuItemCadastroProfessor.setText("Excluir");
        jMenuItemCadastroProfessor.setToolTipText("Excluir pessoas do Cadastro");
        jMenuItemCadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProfessorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroProfessor);

        jMenuItemCadastroAula.setText("Listar");
        jMenuItemCadastroAula.setToolTipText("Listar Cadastrados");
        jMenuItemCadastroAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAulaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroAula);

        jMenuBar.add(jMenuCadastro);

        jMenuFinancas.setText("Finanças");

        jMenuItemMensalidade.setText("Receber Mensalidade");
        jMenuItemMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMensalidadeActionPerformed(evt);
            }
        });
        jMenuFinancas.add(jMenuItemMensalidade);

        jMenuItemPagarConta.setText("Pagar Conta");
        jMenuItemPagarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagarContaActionPerformed(evt);
            }
        });
        jMenuFinancas.add(jMenuItemPagarConta);

        jMenuBar.add(jMenuFinancas);

        jMenuFerramentas.setText("Ferramentas");

        jMenuBemVindo.setText("Bem Vindo");
        jMenuBemVindo.setToolTipText("Chama a tela de bem vindo");
        jMenuBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuBemVindo);

        jMenuEvolucao.setText("Evolução Alunos");
        jMenuEvolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEvolucaoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuEvolucao);

        jMenuDivedores.setText("Relatorio Devedores");
        jMenuDivedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDivedoresActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuDivedores);

        jMenuBalanco.setText("Balanços");
        jMenuBalanco.setEnabled(false);
        jMenuFerramentas.add(jMenuBalanco);

        jMenuBar.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        setSize(new java.awt.Dimension(1014, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarAulaActionPerformed

    private void jMenuItemCadastroalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroalunoActionPerformed
        CadastroIncluir cadaluno = new CadastroIncluir();
       
        TelaBemVindo.hide();
         cadaluno.setVisible(true);
          cadaluno.setAlwaysOnTop(true);
        
    }//GEN-LAST:event_jMenuItemCadastroalunoActionPerformed

    private void jMenuItemMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMensalidadeActionPerformed
        // TODO add your handling code here:
       Mensalidade p = new Mensalidade();
       p.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemMensalidadeActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

            TelaBemVindo.dispose();

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed

        System.exit(0);
        
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBemVindoActionPerformed
        // TODO add your handling code here:
        TelaBemVindo.show();
        
    }//GEN-LAST:event_jMenuBemVindoActionPerformed

    private void jButtonMedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicaoActionPerformed
           Medicao m = new Medicao(0);
           m.setVisible(true);
    }//GEN-LAST:event_jButtonMedicaoActionPerformed

    private void jMenuItemCadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProfessorActionPerformed
        // TODO add your handling code here:
        CadastroExcluir ce = new CadastroExcluir();
        ce.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadastroProfessorActionPerformed

    private void jMenuItemCadastroAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAulaActionPerformed
        // TODO add your handling code here:
        CadastroListar c = new CadastroListar();
        c.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemCadastroAulaActionPerformed

    private void jButtonReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceberActionPerformed
        // TODO add your handling code here:
       Mensalidade p = new Mensalidade();
       p.setVisible(true);
        
    }//GEN-LAST:event_jButtonReceberActionPerformed

    private void jMenuItemPagarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagarContaActionPerformed
        // TODO add your handling code here:
       Lancamento l  = new Lancamento();
       l.setVisible(true);
    }//GEN-LAST:event_jMenuItemPagarContaActionPerformed

    private void jMenuDivedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDivedoresActionPerformed
        // TODO add your handling code here:
        Devedores d = new Devedores();
        d.setVisible(true);
        
    }//GEN-LAST:event_jMenuDivedoresActionPerformed

    private void jMenuEvolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEvolucaoActionPerformed
        // TODO add your handling code here:
        Acompanhamento a = new Acompanhamento();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuEvolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame TelaBemVindo;
    private javax.swing.JButton jButtonIniciarAula;
    private javax.swing.JButton jButtonMedicao;
    private javax.swing.JButton jButtonReceber;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuBalanco;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuBemVindo;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuDivedores;
    private javax.swing.JMenuItem jMenuEvolucao;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenu jMenuFinancas;
    private javax.swing.JMenuItem jMenuItemCadastroAula;
    private javax.swing.JMenuItem jMenuItemCadastroProfessor;
    private javax.swing.JMenuItem jMenuItemCadastroaluno;
    private javax.swing.JMenuItem jMenuItemMensalidade;
    private javax.swing.JMenuItem jMenuItemPagarConta;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelBemVindo;
    // End of variables declaration//GEN-END:variables
}
